### ISSUE TITLE
Restore the http://subl.ee/runker link

### ISSUE THREAD

**Issue by xtendo-org** [sublee/subleerunker#1]
Subleerunker is a videogame masterpiece that enables the poignant experience of avoiding endlessly falling objects, instantly, from everywhere, with nearly no system requirements or installation.

The URL http://subl.ee/runker is dead however, bringing great frustration and disappointment to the globally widespread fans who desperately need the exercise of snaking through the rain of hostile stuff.

**Comment by sublee** [comment]
It's available on https://subl.ee/runker/ now!

**Comment by sublee** [comment]
In addition to that, now it supports mobile browsers with touch controls.  Enjoy!
